services:
  mvca:
    build:
      context: .
      dockerfile: Dockerfile.mvca
    ports:
      - 2121:80
      - 8081:8081
    volumes:
      - ./app:/var/www/mvca
      
  mvca-mariadb:
    build:
      context: .
      dockerfile: Dockerfile.mvca-mariadb
    ports:
      - 2122:3306
    volumes:
      - ./mariadb:/var/lib/mysql
      
  mvca-postgresql:
    build:
      context: .
      dockerfile: Dockerfile.mvca-postgresql
    ports:
      - 2123:5432
    volumes:
      - ./postgresql:/var/lib/postgresql/data